### ISSUE TITLE
Add ability to pass flags to htmlproofer

### ISSUE THREAD

**Issue by abahgat** [CircleCI-Public/hugo-orb#13]
`html-proofer` offers a good number of flags to be specify which tests to enforce. While the defaults assumed in this orb seem sensible, I would like to be able to change them without having to fork the orb.

**Comment by distributedlock** [comment]
I'll take this.

**Comment by FelicianoTech** [comment]
It seems a lot easier here to just use HTML Proofer itself doesn't it?

**Comment by abahgat** [comment]
Honestly, I don't believe so. Passing parameters using a mechanism such as #21 seems to be low overhead and low maintenance and would add a lot of flexibility to having HTML Proofer bundled in the same orb as Hugo.

Lacking a way to pass parameters (e.g. for excluding some paths/files from validation) the present setup can run into trouble as soon as the set of flags that happen to be specified in the orb aren't adequate.
