### ISSUE TITLE
Consider allowing to run html-proofer as a separate step than build

### ISSUE THREAD

**Issue by abahgat** [CircleCI-Public/hugo-orb#15]
This is to enable multiple workflow to trigger independently right after the site is build.
For example, imagine I wanted to validate the generated RSS after the site is built but also run tests. Now the only option seems to be to run this step after html-proofer completes, but that is not ideal for two reasons:

* the workflow will take longer to complete since steps will run sequentially
* HTML errors will prevent RSS validation from running (since it's downstream)

**Comment by FelicianoTech** [comment]
@abahgat This looks to have been addressed?

**Comment by abahgat** [comment]
Yes, thanks!
