### ISSUE TITLE
hugo/install should provide a better error message when passed an invalid version

### ISSUE THREAD

**Issue by remeika** [CircleCI-Public/hugo-orb#26]
## What would you like to be added

The `hugo/install` command should provide a more descriptive error message when the user passes in an invalid version number. 

## Why is this needed

If I attempt to run the command

```yaml
hugo/install:
  version: '0.69'
```

I get the following error output:

```
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Exited with code exit status 2
```

This gives the user very little information on what actually went wrong. 

## Proposed Solution

The script should catch errors at the download/unzip command, and if it fails, check for the existence of the file using the [following strategy](https://stackoverflow.com/a/12199125/2701578); if the file does not exist, give the user a more specific error message.

**Comment by FelicianoTech** [comment]
I agree. Great request, this will be included soon.

**Comment by remeika** [comment]
Great! Let me know if you'd accept a PR for this, or are imminently going to begin work on it.

**Comment by FelicianoTech** [comment]
For this Issue, yes a PR is welcome. :)
