### ISSUE TITLE
hugo/install should allow the user to specify an installation location

### ISSUE THREAD

**Issue by remeika** [CircleCI-Public/hugo-orb#27]
## What would you like to be added

The user should be able to specify a location to unzip the Hugo binary when running `hugo/install`

## Why is this needed

Attempting to run the command `hugo/install` on images based on [`cimg/base`](https://hub.docker.com/r/cimg/base) fails because the image user cannot write to `/usr/local/bin`. Allowing the user to override the install location would allow compatibility with many more base images.

**Comment by FelicianoTech** [comment]
This is actually two issues. Hugo should install fine on cimg/base. That needs to be fixed. Passing an alternative install path is a good idea as well.
