### ISSUE TITLE
The hugo/install command should cache the Hugo binary

### ISSUE THREAD

**Issue by remeika** [CircleCI-Public/hugo-orb#28]
## What would you like to be added

The `Hugo/install` command should cache the Hugo binary

## Why is this needed

Caching the Hugo binary would speed up build time.

## Proposed approach

1. Save the URL that will be used to download Hugo to a file named `hugo.url`
2. Check for a cache with key `hugo/install-{{ checksum hugo.url }}`
1. If cache does not exist, download and uncompress the Hugo binary
3. Cache the Hugo binary and `hugo.url` with the above key.

**Comment by FelicianoTech** [comment]
:+1:
