### ISSUE TITLE
v1.1.0 release not available in Circle CI env (?)

### ISSUE THREAD

**Issue by justwheel** [CircleCI-Public/hugo-orb#42]
### Orb version

1.1.0

### What happened

It is unclear to me if the new version is not available in the environment, or if the `asciidoc` parameter is broken. I ran [this job](https://app.circleci.com/pipelines/github/unicef/inventory/4/workflows/67445359-06bc-42ba-9ba7-9a0e912b7463/jobs/4) from [this commit](https://github.com/unicef/inventory/pull/1/commits/5dc61146eb577c06af2e9e51ab24d25267d27798), but the job failed:

```sh
#!/bin/sh -eo pipefail
# Error calling workflow: 'main'
# Error calling job: 'hugo/build'
# Unexpected argument(s): asciidoc
# 
# -------
# Warning: This configuration was auto-generated to show you the message above.
# Don't rerun this job. Rerunning will have no effect.
false
```

I'm not sure how best to debug this to confirm the root cause of the issue.

### Expected behavior

Job completes successfully with AsciiDoc support enabled.

**Comment by dsayling** [comment]
The latest version with your recent contribution is `1.1.1`, but I see you used that in your config.

In #40, you added `asciidoc` to the [`install` command](https://github.com/CircleCI-Public/hugo-orb/blob/master/src/commands/install.yml#L10). The [build job](https://github.com/CircleCI-Public/hugo-orb/blob/master/src/jobs/build.yml) however does not reference this command.

**Comment by justwheel** [comment]
@dsayling Thanks! I better understand the Circle CI workflow now. I am still migrating over from another platform and learning my way around Circle CI.

I opened #43, which I hope correctly enables the `asciidoc` flag for the `hugo/build` job.
